services:
  fruggr-scanner:
    image: fruggr/scanner:latest
    pull_policy: always
    environment:
      - FRUGGR_API_KEY
      - FRUGGR_AUTH_STEPS
    volumes:
      - "$FRUGGR_AUTH_STEPS:$FRUGGR_AUTH_STEPS"
